export const EDIT_ITEM = 'app/HomePage/EDIT_ITEM'
export const DELETE_ITEM = 'app/HomePage/DELETE_ITEM'
export const DELETE_ITEM_SUCCESS = 'app/HomePage/DELETE_ITEM_SUCCESS'
export const ADD_FAVORITE = 'app/HomePage/ADD_FAVORITE'
export const HANLDE_ITEM_SUCCESS = 'app/HomePage/HANLDE_ITEM_SUCCESS'
export const SAVE_EDIT = 'app/Homepage/SAVE_EDIT'